- name: check_old_app_exist
  shell: docker ps |grep datasearch|awk '{print $1}'
  register: appContainerId
  ignore_errors: True
- name: rmove_app
  shell: '
        docker kill datasearch
        docker rm datasearch
  '
  when: appContainerId != ''
- name: create_app
  shell: 'docker run -d -p 8882:8881 --name datasearch datasearch'

