- name: check_old_app_exist
  shell: docker ps |grep {{ app_env.SERVICE_NAME  }}|awk '{print $1}'
  register: appContainerId
  ignore_errors: True
- name: rmove_app_1
  shell: docker kill {{ app_env.SERVICE_NAME  }}
  when: appContainerId != ''
  ignore_errors: True
- name: rmove_app_2
  shell: docker rm  {{ app_env.SERVICE_NAME  }}
  when: appContainerId != ''
  ignore_errors: True
- name: print_var
  shell: echo {{ appContainerId }}
- name: create_app
  shell: 'docker run -d -p {{ app_env.HTTP_PORT }}:{{ app_env.HTTP_PORT  }} --name {{ app_env.SERVICE_NAME  }} johnking123/{{ app_env.SERVICE_NAME  }}'
- name: remove_old_images
  shell: docker images|grep none|xargs docker rmi -f
  ignore_errors: True