- hosts: redhatGroup
  user: root
  vars:
    skip_remove_apps: false
    skip_create_apps: false
    skip_run_apps: false

  # vars_files:
  #   - env_vars/{{env | default('dev') }}.yml

  #environment: "{{app_env}}"

  roles:
  - name: tiger
